version: "3.9"
services:
    server:
        build: ./server
        ports:
            - "5000:5000"
    client:
        build: ./client
        network_mode: host
        depends_on:
            - server